name: book_grocer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.69.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/img/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  
  # example:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-ThinItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
  #   - family: Trajan Pro
